### ISSUE TITLE
Add public API support for mi_posix_memalign

### ISSUE THREAD

**Issue by jq-rs** [purpleprotocol/mimalloc_rust#43]
Please add support for
```
    pub fn mi_calloc(count: usize, size: usize) -> *mut c_void;
    pub fn mi_posix_memalign(ptr: *mut *mut c_void, alignment: usize, size: usize) -> c_int;
```
so that this crate could be used with Rust compiler as an allocator replacement.

**Comment by thomcc** [comment]
mi_calloc is here: https://github.com/purpleprotocol/mimalloc_rust/blob/master/libmimalloc-sys/src/extended.rs#L17

In the same file and elsewhere you'll find many mi_aligned_alloc fucntions which are more powerful and less error prone than the posix_memalign replacement.

**Comment by jq-rs** [comment]
Thanks. The external malloc API in rustc assumes support for posix_memalign. I am not aware of is it easy to change it to something else.

**Comment by thomcc** [comment]
Hm? I have a patch somewhere that does this, it's definitely possible.

Worth noting that overriding malloc statically only works well on non-apple unixes though.

**Comment by thomcc** [comment]
That said it's probably reasonable to add mi_posix_memalign for others who are stuck figuring out how to override something.

Note that you shouldn't use the override feature of this crate, though. It shouldn't have been added since for the most part it just enables functionality of the cmake build that is designed for producing a DLL that overrides malloc when set in the env.

**Comment by jq-rs** [comment]
Great, thanks! A new minor version published to crates.io would be awesome after this extension.
