### ISSUE TITLE
0.1.35 not available on crates.io

### ISSUE THREAD

**Issue by gitmalong** [purpleprotocol/mimalloc_rust#93]

**Comment by NobodyXu** [comment]
It's yanked due to bug reported in #92

**Comment by NobodyXu** [comment]
It's yanked due to bug reported in #92

**Comment by Keavon** [comment]
@NobodyXu if I'm understanding all the pieces at play here, shouldn't [libmimalloc-sys 0.1.31](https://crates.io/crates/libmimalloc-sys/0.1.31) have been yanked instead of [mimalloc 0.1.35](https://crates.io/crates/mimalloc/0.1.35)? Since both 0.1.34 and 0.1.35 [depend on](https://deps.rs/crate/mimalloc/0.1.34) `^0.1.30` which matches 0.1.31 in this case.

If my analysis is correct here, could a maintainer please un-yank (if possible) the `mimalloc` version and yank the `libmimalloc-sys` version? @octavonce

Thanks :)

**Comment by octavonce** [comment]
`v0.1.36` is now released
